'use client';
import GlobalStyle from '@/Styles/globals';
import { useTranslations } from 'next-intl';
import React from 'react';
import Header from '@/components/Header/Header';
import { useSearchParams } from 'next/navigation';

const metadata = {
   title: 'Games By | Catalog',
   description: 'Generated by create next app',
};
const Catalog = () => {
   const t = useTranslations('Index');
   const searchParams = useSearchParams();
   const searched = searchParams.get('searched') || '';
   return (
      <>
         <GlobalStyle />
         <Header />
         <h1>Catalog</h1>
         <p>Search term: {searched}</p>
      </>
   );
};

export default Catalog;
