'use client';
import GlobalStyle from '@/Styles/globals';
import { useTranslations } from 'next-intl';
import React from 'react';
import Header from '@/components/Header/Header';
import { useSearchParams } from 'next/navigation';

// export const metadata = {
//    title: 'Games By | GamePage',
//    description: 'Generated by create next app',
// };
const GamePage = () => {
   const t = useTranslations('Index');
   const searchParams = useSearchParams();
   const searched = searchParams.get('searched') || '';
   return (
      <>
         <GlobalStyle />
         <Header />
         <h1>GamePage</h1>
         <p>Search term: {searched}</p>
      </>
   );
};

export default GamePage;
