import { useTranslations } from 'next-intl';
import LanguageSwitcher from '@/components/Languages/LanguageSwitcher';
import React from 'react';
import Header from '@/components/Header/Header';

export const metadata = {
   title: "Games By | Login",
   description: "Generated by create next app",
};

export default function LoginPage() {
   const t = useTranslations('Index');
   return (
      <>
         <h1>Login</h1>
      </>
   );
}
